- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- package-lock.json
- package.json
1. Added Contribution guidelines.
2. Added Code of conduct.
3. Added introduction video link.
4. Added PR and commit message templates.
> Update Readme #12

- .prettierignore
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- format.json
- package-lock.json
- package.json
- src/fileUtils.js
- src/server.js
ADDED Husky and prettier
Because:
- Prettier is for code formatting.
- Husky for pre-commit hooks
> Added Prettier as pre-commit hook #22

- CONTRIBUTING.md
- README.md
With reference to issue #26 
I have updated the contributing.md file and added a link to our discord server in README file
Also added the following -
1. Difference between GIT and GITHUB
2. How to clone,fork repository
3. How to create a branch and then use git push to push to repo
4. Create a PR
5. Squash commits in a single issue into one
6. Updating the forked and local repo as the updations are made in the upstream
@learneradarsh @kaushik-rishi Have a look!
> Update the contributing.md and add link in README file

- src/commands.json
- src/executor.js
- refactored using colors to chalk modules
- refactored the execute function to execute based on the problem directory
> Implement test case execution based on all the files in the test case folder

- .talismanrc
- package-lock.json
- package.json
- src/app.js
[Issue#43] Execute Server js on CLI command rcp
Because:
- To start cli feature to run the server using cli
> CLI argument rcp added

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/general_issue.md
- .github/PULL_REQUEST_TEMPLATE.md
> [qa] Add:Issue and PR template

- .eslintrc.json
- src/executor.js
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue no.)
NA
> eslint bug fix

- src/configuration/routes/index.js
- src/configuration/server.js
Created a new file routes/index and shifted all the routes there.
Fixes #84
@kaushik-rishi
> Routes Arrange ment

- src/configuration/routes/index.js
- src/configuration/server.js
Added express body parser in src/configuration/server.js
Fixes #86 
@kaushik-rishi
> Bug body parser

- src/app.js
- src/configuration/routes/index.js
- src/configuration/server.js
- src/serverUtils/loadconfig.js
Added a load config file in utils folder and required it in app.js
Fixes #89 
@kaushik-rishi
> Feature read config

- src/configuration/routes/index.js
- src/configuration/server.js
Added a route to store
Fixes #34 
@kaushik-rishi
> Feature store config

- src/app.js
- src/configuration/routes/index.js
- src/configuration/server.js
- src/serverUtils/defaultconfig.json
- src/serverUtils/loadconfig.js
Added  a default config.json file.
Fixes #91 
@kaushik-rishi
> Feature default config

- src/serverUtils/codeLib.json
- src/serverUtils/loadconfig.js
Added a CodeLib.json including everything of every lang. 
Fixes #93 
@kaushik-rishi
> Code Library Added

- src/configuration/routes/index.js
Added a get template route.
Fixes #110 
@kaushik-rishi
> Added a get template route in configuration server

- .eslintrc.json
- src/app.js
- src/configuration/routes/index.js
- src/executor/diffChecker.js
- src/executor/index.js
- src/parser/index.js
- src/parser/utils.js
- src/serverUtils/defaultconfig.js
Implemented default config in main server.js
Fixes #116 
@kaushik-rishi
> Implement config server

- .eslintrc.json
- src/app.js
- src/configuration/routes/index.js
- src/executor/diffChecker.js
- src/executor/index.js
- src/parser/index.js
- src/parser/utils.js
- src/serverUtils/defaultconfig.js
Storing all problems in a contest wise organized manner.
Fixes #121 
@kaushik-rishi
> Store contest dir

- src/executor/index.js
implemented arguments in Executor
> implemented arguments in Executor

- src/executor/diffChecker.js
- src/executor/index.js
> Bug get difference

- package-lock.json
- package.json
- src/app.js
- src/executor/diffChecker.js
- src/executor/execute.js
- src/executor/index.js
Refactored execute as it was becoming too complex
> Refactor execute

- src/templates/codes/cppAdv.txt
Added a advance template for cpp
> Added a advance template for cpp

- src/serverUtils/codeLib.json
- src/templates/codes/cppAdv.txt
Implemented a advance template for app
> Implement template cpp adv

- src/serverUtils/codeLib.json
- src/templates/codes/cppAdv.txt
- src/templates/codes/cppInter.txt
Added a intermediate template for cpp
> Template cpp intermediate

- src/serverUtils/codeLib.json
- src/templates/codes/cppAdv.txt
- src/templates/codes/cppInter.txt
Implemented a intermediate template for cpp
> Implement template cpp intermediate

- src/serverUtils/codeLib.json
- src/templates/codes/c.txt
- src/templates/codes/cppAdv.txt
- src/templates/codes/cppInter.txt
> Template c basic

- src/serverUtils/codeLib.json
- src/templates/codes/c.txt
- src/templates/codes/cppAdv.txt
- src/templates/codes/cppInter.txt
Implemented a basic template for c
> Implement template c basic

- src/serverUtils/codeLib.json
- src/templates/codes/c.txt
- src/templates/codes/cInter.txt
- src/templates/codes/cppAdv.txt
- src/templates/codes/cppInter.txt
Implemented intermediate template for c
> Implement template c intermediate

- src/serverUtils/argParser.js
Removed unnesecary check in dir option
> Removed unnesecary check in dir option

- package-lock.json
- package.json
- src/configuration/server.js
- src/serverUtils/argParser.js
- src/serverUtils/protocol.js
Added protocol registration on init
> Protocol registry

- package-lock.json
- package.json
- src/configuration/server.js
- src/serverUtils/argParser.js
- src/serverUtils/protocol.js
Added url argument in arg parser.
> Url args add

- package-lock.json
- package.json
- src/configuration/server.js
- src/serverUtils/argParser.js
- src/serverUtils/protocol.js
Added url parser to decode incoming url
> Url parser

- package-lock.json
- package.json
- src/configuration/server.js
- src/serverUtils/argParser.js
- src/serverUtils/protocol.js
- src/templates/codes/java.java
Added a Basic template for java
> Template java basic

- package-lock.json
- package.json
- src/configuration/server.js
- src/serverUtils/argParser.js
- src/serverUtils/codeLib.json
- src/serverUtils/protocol.js
- src/templates/codes/java.java
Implemented a basic templete template for java
> Implement template java basic

- package-lock.json
- package.json
- src/configuration/server.js
- src/serverUtils/argParser.js
- src/serverUtils/codeLib.json
- src/serverUtils/protocol.js
- src/templates/codes/java.java
- src/templates/codes/javaInter.java
Added a intermediate template for java.
> Template java intermediate

- package-lock.json
- package.json
- src/configuration/server.js
- src/serverUtils/argParser.js
- src/serverUtils/codeLib.json
- src/serverUtils/protocol.js
- src/templates/codes/java.java
- src/templates/codes/javaInter.java
Implemented the Intermediate template for java
> Implement template java intermediate

- package-lock.json
- package.json
- src/configuration/server.js
- src/serverUtils/argParser.js
- src/serverUtils/codeLib.json
- src/serverUtils/protocol.js
- src/templates/codes/java.java
- src/templates/codes/javaAdv.java
- src/templates/codes/javaInter.java
Added a advance template for java
> Template java advance

- package-lock.json
- package.json
- src/configuration/server.js
- src/serverUtils/argParser.js
- src/serverUtils/codeLib.json
- src/serverUtils/protocol.js
- src/templates/codes/java.java
- src/templates/codes/javaAdv.java
- src/templates/codes/javaInter.java
Implemented a advance template for Java
> Implement template java advance

- package-lock.json
- package.json
- src/configuration/server.js
- src/serverUtils/argParser.js
- src/serverUtils/codeLib.json
- src/serverUtils/protocol.js
- src/templates/codes/java.java
- src/templates/codes/javaAdv.java
- src/templates/codes/javaInter.java
- src/templates/codes/pythonInter.py
Added a Intermediate template for python
> Template python intermediate

- package-lock.json
- package.json
- src/configuration/server.js
- src/serverUtils/argParser.js
- src/serverUtils/codeLib.json
- src/serverUtils/protocol.js
- src/templates/codes/java.java
- src/templates/codes/javaAdv.java
- src/templates/codes/javaInter.java
- src/templates/codes/pythonInter.py
Implemented a Intermediate template for python
> Implement template python intermediate

- src/serverUtils/protocol.js
Added  Lang query parser in url parser
> added lang query parser in url parser

- src/serverUtils/protocol.js
Added dir Support in url parser
> Url parser dir

- src/serverUtils/protocol.js
Added watch feature in url parser
> Url parser watch

- src/serverUtils/protocol.js
Added interactive query parser in url parser
> Url parser interactive

- src/serverUtils/protocol.js
added show-diff query parser in url parser
> Url parser show diff

- src/serverUtils/argParser.js
- src/serverUtils/protocol.js
- src/serverUtils/urlParser.js
Refactored url parser to a different file for modulating the code
> Refactor url parser

- package-lock.json
- package.json
- src/serverUtils/argParser.js
- src/serverUtils/protocol.js
- src/serverUtils/urlParser.js
Improved Protocol registry mechanism for script
> Protocol registry improved

- README.md
Corrected a typo 
Fixes #186 
-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] I have made corresponding changes to the documentation.
-   [ ] My changes generate no new warnings.
> Corrected typo in Readme
